Service:
  RegionId: cn-hangzhou
  DeployType: ros
  OperationMetadata:
    StatusOperationConfigs:
      - TemplateName: ECS单机版
        SupportOperations:
          - Start
          - Stop
          - Restart
    SupportBackup: true
    ModifyParametersConfig:
      - TemplateName: ECS单机版
        Operation:
          - Name: 变更ECS实例规格
            Description: 变更ECS实例规格
            Type: Custom
            Parameters:
              - EcsInstanceType
          - Name: 变更ECS实例密码
            Description: 变更ECS实例密码
            Type: Custom
            Parameters:
              - InstancePassword
  DeployMetadata:
    SupplierDeployMetadata:
      SupplierTemplateConfigs:
        - Name: ECS单机版
          Url: 'ros_templates/template.yaml'
          ArchitectureDiagramUrl: 'resources/architecture/architecture.jpg'
          AllowedRegions:
            - ap-southeast-1
      ArtifactRelation:
        ecs_image_langfuse:
          ArtifactId: ${Artifact.EcsImage.ArtifactId}
          ArtifactVersion: draft
    TemplateConfigs:
      - Name: ECS单机版
        Url: 'ros_templates/template.yaml'
        ArchitectureDiagramUrl: 'resources/architecture/architecture.jpg'
        AllowedRegions:
          - ap-southeast-1
  ServiceType: private
  ServiceInfo:
    # 英文版可以再配置Locale为en-US的服务信息
    - Locale: zh-CN
      ShortDescription: demo
      Image: 'resources/icons/service_logo.png'
Artifact:
  EcsImage:
    ArtifactType: EcsImage
    ArtifactName: ecs_image_langfuse
    Description: langfuse EcsImage
    SupportRegionIds:
        - ap-southeast-1
    ArtifactBuildProperty:
      CodeRepo:
        Platform: github
        Owner: JJGGu
        RepoName: JJGGu/langfuse
        Branch: main
      RegionId: ap-southeast-1
      CommandType: RunShellScript
      SourceImageId: 
      CommandContent: |-
        mkdir -p /root/application
        if [ -e "/root/code/langfuse_clickhouse_logs" ]; then cp -r "/root/code/langfuse_clickhouse_logs" "/root/application/"; fi
        if [ -e "/root/code/langfuse_postgres_data" ]; then cp -r "/root/code/langfuse_postgres_data" "/root/application/"; fi
        if [ -e "/root/code/docker-compose.yml" ]; then cp -r "/root/code/docker-compose.yml" "/root/application/"; fi
        if [ -e "/root/code/.env.prod.example" ]; then cp -r "/root/code/.env.prod.example" "/root/application/"; fi
        if [ -e "/root/code/langfuse_clickhouse_data" ]; then cp -r "/root/code/langfuse_clickhouse_data" "/root/application/"; fi
        if [ -e "/root/code/langfuse_minio_data" ]; then cp -r "/root/code/langfuse_minio_data" "/root/application/"; fi
        cd /root/application
        cp .env.prod.example ./.env
        sed -i 's/pull_policy: always/pull_policy: if_not_present/g' docker-compose.yml
        docker compose -f docker-compose.yml build
        docker compose -f docker-compose.yml pull || true;